name: packing
on:
  push:
    tags:
      - "v*"

jobs:
  
  pack_linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
          cd solver_application/
          cmake -B build
          cmake --build build
        
      - name: pack TGZ
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G TGZ
          cd ../..
          mv solver_application/build/*.tar.gz artifacts
          
      - name: deploy
        uses: actions/upload-artifact@v3
        with:
          path: artifacts/*tar.gz
          
      - name: pack ZIP
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G ZIP          
          cd ..
          mv build/*.zip artifacts
          
      - name: pack DEB
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G DEB
          cd ..
          mv build/*.deb artifacts
          
      - name: pack RPM
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G RPM
          cd ..
          mv build/*.rpm artifacts
        
  pack_macos:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
          cd solver_application/
          cmake -B build
          cmake --build build

      - name: pack DMG
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G DragNDrop
          cd ..
          mv build/*.dmg artifacts
          
  pack_windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
          cd solver_application/
          cmake -B build
          cmake --build build
          
      - name: pack MSI
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G WIX
          cd ..
          mv build/*.msi artifacts
