name: packing
on:
  push:
    tags:
      - "v*"

jobs:
  
  pack_linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
          cd solver_application/
          cmake -B build
          cmake --build build
        
      - name: pack TGZ
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G TGZ
          cd ../..
          mv solver_application/build/*.tar.gz artifacts
          
      - name: pack ZIP
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G ZIP          
          cd ../..
          mv solver_application/build/*.zip artifacts
          
      - name: pack DEB
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G DEB
          cd ../..
          mv solver_application/build/*.deb artifacts
          
      - name: pack RPM
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G RPM
          cd ../..
          mv solver_application/build/*.rpm artifacts
          
      - name: push on
        shell: bash
        run: |
          git config --global user.name "IvanGalk1n
          git config --global user.email "ivangalkin0720@gmail.com"
          cd artifacts/
          git add *.deb *.rpm
          git commit -m "added deb & rpm"
          git push origin master
        
  pack_macos:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
          cd solver_application/
          cmake -B build
          cmake --build build

      - name: pack DMG
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G DragNDrop
          cd ../..
          mv solver_application/build/*.dmg artifacts
          
  pack_windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
          cd solver_application/
          cmake -B build
          cmake --build build
          
      - name: pack MSI
        run: |
          cd solver_application/build/
          cpack -G WIX
          cd ../..
          mv solver_application/build/*.msi artifacts
